import 'package:flutter/material.dart';import 'package:hotel_booking/core/app_export.dart';import 'package:hotel_booking/widgets/custom_elevated_button.dart';import 'package:smooth_page_indicator/smooth_page_indicator.dart';class OnboardingOneScreen extends StatelessWidget {const OnboardingOneScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(body: SizedBox(width: double.maxFinite, child: Column(children: [CustomImageView(imagePath: ImageConstant.imgRectangle1420x428, height: 420.v, width: 428.h), SizedBox(height: 37.v), _buildInfo(context), SizedBox(height: 98.v), SizedBox(height: 8.v, child: AnimatedSmoothIndicator(activeIndex: 0, count: 3, effect: ScrollingDotsEffect(spacing: 6, activeDotColor: theme.colorScheme.primary, dotColor: appTheme.blueGray900, dotHeight: 8.v, dotWidth: 8.h))), SizedBox(height: 32.v), _buildFiftyOne(context), SizedBox(height: 5.v)])))); } 
/// Section Widget
Widget _buildInfo(BuildContext context) { return Container(padding: EdgeInsets.symmetric(horizontal: 43.h), child: Column(children: [Container(width: 307.h, margin: EdgeInsets.only(left: 16.h, right: 17.h), child: Text("Travel safely, comfortably, & easily", maxLines: 2, overflow: TextOverflow.ellipsis, textAlign: TextAlign.center, style: theme.textTheme.headlineLarge!.copyWith(height: 1.50))), SizedBox(height: 6.v), SizedBox(width: 341.h, child: Text("Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", maxLines: 3, overflow: TextOverflow.ellipsis, textAlign: TextAlign.center, style: CustomTextStyles.bodyLarge18.copyWith(height: 1.50)))])); } 
/// Section Widget
Widget _buildFiftyOne(BuildContext context) { return Padding(padding: EdgeInsets.symmetric(horizontal: 24.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomElevatedButton(width: 180.h, text: "Skip", buttonStyle: CustomButtonStyles.fillBlueGray, onPressed: () {onTapSkip(context);}), CustomElevatedButton(width: 180.h, text: "Next", margin: EdgeInsets.only(left: 20.h), onPressed: () {onTapNext(context);})])); } 
/// Navigates to the letSYouInScreen when the action is triggered.
onTapSkip(BuildContext context) { Navigator.pushNamed(context, AppRoutes.letSYouInScreen); } 
/// Navigates to the onboardingTwoScreen when the action is triggered.
onTapNext(BuildContext context) { Navigator.pushNamed(context, AppRoutes.onboardingTwoScreen); } 
 }
