import '../my_bookmarks_screen/widgets/mybookmarks_item_widget.dart';import 'package:flutter/material.dart';import 'package:hotel_booking/core/app_export.dart';import 'package:hotel_booking/widgets/app_bar/appbar_leading_image.dart';import 'package:hotel_booking/widgets/app_bar/appbar_title.dart';import 'package:hotel_booking/widgets/app_bar/appbar_trailing_iconbutton_one.dart';import 'package:hotel_booking/widgets/app_bar/appbar_trailing_image.dart';import 'package:hotel_booking/widgets/app_bar/custom_app_bar.dart';class MyBookmarksScreen extends StatelessWidget {const MyBookmarksScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: SizedBox(width: SizeUtils.width, child: SingleChildScrollView(padding: EdgeInsets.only(top: 24.v), child: Padding(padding: EdgeInsets.symmetric(horizontal: 24.h), child: Column(children: [_buildMyBookmarks(context), SizedBox(height: 24.v), _buildPresidentMilaDe(context)])))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 52.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowDown, margin: EdgeInsets.only(left: 24.h, top: 11.v, bottom: 16.v), onTap: () {onTapArrowDown(context);}), title: AppbarTitle(text: "My Bookmarks", margin: EdgeInsets.only(left: 16.h)), actions: [AppbarTrailingIconbuttonOne(imagePath: ImageConstant.imgMegaphone, margin: EdgeInsets.only(left: 24.h, top: 11.v, right: 16.h)), AppbarTrailingImage(imagePath: ImageConstant.imgGridPrimary, margin: EdgeInsets.only(left: 20.h, top: 11.v, right: 40.h))]); } 
/// Section Widget
Widget _buildMyBookmarks(BuildContext context) { return GridView.builder(shrinkWrap: true, gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(mainAxisExtent: 281.v, crossAxisCount: 2, mainAxisSpacing: 0.h, crossAxisSpacing: 0.h), physics: NeverScrollableScrollPhysics(), itemCount: 4, itemBuilder: (context, index) {return MybookmarksItemWidget(onTapImgImage: () {onTapImgImage(context);});}); } 
/// Section Widget
Widget _buildPresidentMilaDe(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.center, children: [Padding(padding: EdgeInsets.only(right: 12.h), child: _buildTypeCardThemeDark(context)), Padding(padding: EdgeInsets.only(left: 12.h), child: _buildTypeCardThemeDark(context))]); } 
/// Common widget
Widget _buildTypeCardThemeDark(BuildContext context) { return Expanded(child: SizedBox(width: double.maxFinite, child: Container(padding: EdgeInsets.symmetric(horizontal: 18.h, vertical: 20.v), decoration: AppDecoration.outlineBlackC.copyWith(borderRadius: BorderRadiusStyle.roundedBorder20), child: Column(mainAxisSize: MainAxisSize.min, children: [CustomImageView(imagePath: ImageConstant.imgRectangle5, height: 120.v, width: 140.h, radius: BorderRadius.circular(16.h)), SizedBox(height: 18.v), SizedBox(width: 138.h, child: Text("Martinez Cannes Hotel", maxLines: 2, overflow: TextOverflow.ellipsis, style: theme.textTheme.titleMedium!.copyWith(height: 1.50))), SizedBox(width: 140.h, child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: ImageConstant.imgSignalYellowA700, height: 12.adaptSize, width: 12.adaptSize, margin: EdgeInsets.only(top: 4.v, bottom: 5.v)), Text("4.8", textAlign: TextAlign.center, style: CustomTextStyles.titleSmallPrimary), Padding(padding: EdgeInsets.only(top: 3.v, bottom: 4.v), child: Text("Paris, France", style: CustomTextStyles.bodySmall_1))])), SizedBox(height: 2.v), SizedBox(width: 140.h, child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text("35", style: CustomTextStyles.titleLargePrimary), Padding(padding: EdgeInsets.symmetric(vertical: 3.v), child: Text("/ night", style: CustomTextStyles.bodySmall10)), CustomImageView(imagePath: ImageConstant.imgBookmarkPrimary, height: 24.adaptSize, width: 24.adaptSize)]))])))); } 
onTapImgImage(BuildContext context) {  } 

/// Navigates back to the previous screen.
onTapArrowDown(BuildContext context) { Navigator.pop(context); } 
 }
